services:
  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
  embedding:
    build: .
    image: embedding_server
    container_name: embedding_server
    # restart: always
    ports:
      - ${PORTS:-8000}:8000
    volumes:
      - models:/root/.cache
    environment:
      MODEL_NAME: ${MODEL_NAME:-paraphrase-multilingual-MiniLM-L12-v2}

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - redis
volumes:
  models:
